### ISSUE TITLE
rename() is failing for files > 2MB

### ISSUE THREAD

**Issue by etorofiev** [esbenp/fineuploader-server#2]
```
[2015-09-10 09:08:43] production.ERROR: exception 'ErrorException' with message 'rename(): No such file or directory' in /home/forge/default/vendor/optimus/fineuploa
der-server/src/Uploader.php:69
Stack trace:
#0 (): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/forge/default/vendor/optimus/fineuploader-server/src/Uploader.php(69): rename()
#2 /home/forge/default/vendor/optimus/fineuploader-server/src/Controller/LaravelController.php(27): Optimus\FineuploaderServer\Uploader->upload()
#3 (): Optimus\FineuploaderServer\Controller\LaravelController->upload()
```

**Comment by esbenp** [comment]
This happens for chunked uploads. Will make a PR

**Comment by esbenp** [comment]
b1e8292457634ffdc14e61e96014be789a40d26f
